version: '2'
services:
    vapp4back:
     image: vapp4back
     build: 
      context: .
      dockerfile: Backend/Dockerfile
     ports:
      - "8003:8003"

    vapp4proxy:
     image: vapp4proxy
     depends_on:
      - vapp4back
     build: 
      context: .
      dockerfile: vf-os-vapp-3.4-master/dev/Dockerfile
     ports:
      - "3000:3000"

    vapp4front:
     image: vapp4front
     depends_on:
      - vapp4proxy
     build: 
      context: .
      dockerfile: vf-os-vapp-3.4-master/vapp4/Dockerfile
     ports:
      - "4200:4200"