version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./endpoints.yml:/app/swagger.yml:ro
    ports:
      - 3000:3000
    environment:
      SWAGGER_JSON: /app/swagger.yml
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8081:8080
